### ISSUE TITLE
Windows suggestions stops working in 16.3

### ISSUE THREAD

**Issue by EdiDD** [domferr/tilingshell#305]
**Describe the bug**
After update to 16.3 none of the suggestions works anymore neither tiling nor snap nor egde

**To Reproduce**
Enable any of suggestions

**Information (please complete the following):**
 - Tiling Shell version: 16.3
 - GNOME version: 48

**Comment by domferr** [comment]
Hey, this is strange, thank you for sharing! I am not able to reproduce the problem, since it is working when I enable any of the suggestions. Do you see any other issues which may cause this bug?

**Comment by h44z** [comment]
@domferr the error message I can see in the log is as follows:

```
Mär 30 21:43:27 coreship gnome-shell[1716]: Error in size change accounting.
Mär 30 21:43:28 coreship gnome-shell[1716]: Error in size change accounting.
Mär 30 21:43:31 coreship gnome-shell[1716]: Error in size change accounting.
Mär 30 21:43:33 coreship gnome-shell[1716]: Error in size change accounting.
Mär 30 21:43:35 coreship gnome-shell[1716]: JS ERROR: TypeError: this._scrollView.get_hscroll_bar is not a function
                                           SuggestionsTilePreview@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:3508:22
                                           buildTile@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:3654:12
                                           draw_layout/this._previews<@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:1276:19
                                           draw_layout@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:1253:41
                                           relayout@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:1320:10
                                           _openWindowsSuggestions@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:4521:35
                                           _onWindowGrabEnd@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:4493:10
                                           enable/<@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:4013:14
                                           @resource:///org/gnome/shell/ui/init.js:21:20
Mär 30 21:43:35 coreship gnome-shell[1716]: Error in size change accounting.
```

**Comment by EdiDD** [comment]
@domferr I can't see any other issue and moreover there is nothing in logs. Suggestions just don't work without any other errors

**Comment by domferr** [comment]
Thank you! Can you confirm the issue is solved?

For GNOME 45+: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/19720102/tilingshell%40ferrarodomenico.com.zip)

**Comment by h44z** [comment]
@domferr for me, this release made it worse. A blue area stays on the screen as soon as I tile one window, see screenshots. After that, window management is broken.

![Image](https://github.com/user-attachments/assets/24284c03-dcec-4b75-81c5-6226899bc48f)

![Image](https://github.com/user-attachments/assets/e4a24116-7e43-4e3a-b219-47094102eff3)

**Comment by domferr** [comment]
Thank you @h44z, did you notice any particular log or error? Can you share how I can reproduce this problem?

**Comment by h44z** [comment]
@domferr just tried it again, and there is an error message:

```
Apr 12 22:56:41 obelix gnome-shell[3518]: g_object_set_is_valid_property: construct property "window-container" for object 'PopupWindowPreview' can't be set after construction
Apr 12 22:56:41 obelix gnome-shell[3518]: JS ERROR: TypeError: this.window_container is null
                                          _addWindow@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:3191:5
                                          SuggestedWindowPreview@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:3051:10
                                          _recursivelyShowPopup/clones<@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:3743:24
                                          _recursivelyShowPopup@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:3742:36
                                          open@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:3689:10
                                          _openWindowsSuggestions@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:4543:35
                                          _onWindowGrabEnd@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:4514:10
                                          enable/<@file:///home/h44z/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/extension.js:4034:14
                                          @resource:///org/gnome/shell/ui/init.js:21:20
```

To reproduce this, simply open two windows, resize them so that they float freely, and then drag one window to a tiled section (it does not matter if you use the top bar or press control). Once the window is in its tile, the remaining tiles are highlighted in blue and everything is unresponsive.

**Comment by domferr** [comment]
Thanks a million @h44z! I'm having issues running my GNOME 48 OS virtual machine and your insights really helped!

**Comment by domferr** [comment]
Here it is a fix! Let me know if it works, thank you!

[tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/19856248/tilingshell%40ferrarodomenico.com.zip)

**Comment by domferr** [comment]
Thank you for your feedback! @shdwchn10 yeah, that feature is currently not implemented

**Comment by domferr** [comment]
Fixed by Tiling Shell v16.4! 🌟 
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
